/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class SMIcons {
  SMIcons._();

  static const _kFontFam = 'SM';

  static const IconData behance = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData blogger = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cc = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData delicious = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData deviantart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData digg = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData dribbble = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData flickr = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData foursquare = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData friendfeed = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData friendfeed_rect = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData github_text = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData googleplus = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData path = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData picasa = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData pinterest = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData reddit = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData slideshare = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData stackoverflow = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData stumbleupon = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData tumblr = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData vimeo = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData vkontakte = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData wordpress = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xe81e, fontFamily: _kFontFam);
}
